apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: dreams.good.night  # <plural>.<group>  (lower case!!)
spec:
  group: good.night               # Your API group
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                image:
                  type: string
                  description: Docker image to use for the Deployment.
                  default: nginx:latest
                schedulerName:
                  type: string
                  description: The scheduler to use for the deployment's pods.
            namespace:         #ADDED
              type: string
              description: Namespace of CR

  scope: Namespaced # or Cluster
  names:
    plural: dreams       # The plural name to use in URLs:  /apis/<group>/<version>/<plural>
    singular: dream     # The singular name to use as an alias on the CLI and for display
    kind: Dream           # The kind for the resource to use in manifests
    shortNames:
      - ktl # short name