apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: dream-runai
subjects:
- kind: ServiceAccount
  name: pod-grouper
  namespace: runai
roleRef:
  kind: ClusterRole
  name: dream-controller-role
  apiGroup: rbac.authorization.k8s.io
