apiVersion: v1
kind: Service
metadata:
  name: pvc-size-validator
  namespace: webhooks
spec:
  ports:
  - name: webhook
    port: 443
    targetPort: 8443
  selector:
    app: pvc-size-validator
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pvc-size-validator
  namespace: webhooks
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pvc-size-validator
  template:
    metadata:
      labels:
        app: pvc-size-validator
    spec:
      containers:
      - name: webhook
        image: python:3.9-slim
        ports:
        - containerPort: 8443
        command: ["sh", "-c"]
        args:
          - |
            pip install flask &&
            python /app/server.py
        volumeMounts:
        - name: webhook-config
          mountPath: /app
        - name: webhook-tls
          mountPath: "/app/certs"
          readOnly: true
      volumes:
      - name: webhook-config
        configMap:
          name: webhook-server
      - name: webhook-tls
        secret:
          secretName: webhook-tls
          items:
            - key: tls.crt
              path: webhook.crt
            - key: tls.key
              path: webhook.key
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: pvc-size-validator
webhooks:
  - name: pvc-size-validator.itay.lolz
    clientConfig:
      service:
        name: pvc-size-validator
        namespace: webhooks
        path: /validate
        port: 443
      caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURSekNDQWkrZ0F3SUJBZ0lVVjlqNkJlaVZSR0RQSVN4VUgwK2s0b0lZS2djd0RRWUpLb1pJaHZjTkFRRUwKQlFBd0tqRW9NQ1lHQTFVRUF3d2ZjSFpqTFhOcGVtVXRkbUZzYVdSaGRHOXlMbmRsWW1odmIydHpMbk4yWXpBZQpGdzB5TlRBeE16RXhOREkwTkRoYUZ3MHlOakF4TXpFeE5ESTBORGhhTUNveEtEQW1CZ05WQkFNTUgzQjJZeTF6CmFYcGxMWFpoYkdsa1lYUnZjaTUzWldKb2IyOXJjeTV6ZG1Nd2dnRWlNQTBHQ1NxR1NJYjNEUUVCQVFVQUE0SUIKRHdBd2dnRUtBb0lCQVFDLzk1dmpUTHpFS2c4T1FSajA0RGZwa2VBQk9PUWltWi9BQlhvRzJRTk1sT2pqWlg4dAp0N1NVa2kvUUNwRkZGQ1k5Q0N5WDZIOWo3azA3SDl0T3BoSkRoUXZmTnk2YlhLcHJVRzRIYWpMWjVFU0dNd2VWCmo0R2pPWS9lZUlaNHhpSWJaMjlLUDNVNldUandvNy94bjhpRy9TSzJDRm5UTm5TaEVKZGFyWXYxMm0weUNwOVEKNGtZRmpXbDlvbTJ3YTM0a2ZCRHVhb1dkdE5BZTdPS25VblRDcTg2c0VvRzhWU0Q1WUdCTGxtbWx1YmpHdlN5ZgpCam1zTFZsMVBlenljWUlIcG5yL3BMaTJrUHl1VmdtaE42RytwNlhPOW1IdkcxMUZRa3JETENMMXYwaEF4R1hyCnNSWklmR0tRalBVVURyeUlhTHl2L1BJN29tZEdPclJ0bStxRkFnTUJBQUdqWlRCak1Ba0dBMVVkRXdRQ01BQXcKQ3dZRFZSMFBCQVFEQWdYZ01Db0dBMVVkRVFRak1DR0NIM0IyWXkxemFYcGxMWFpoYkdsa1lYUnZjaTUzWldKbwpiMjlyY3k1emRtTXdIUVlEVlIwT0JCWUVGSlJGM3N3dTVuWTZxYnRiWnlyM3AzUldVaG9CTUEwR0NTcUdTSWIzCkRRRUJDd1VBQTRJQkFRQUlxcHhoRThIa29aeVVZZ2ZQTzByWW1kTy9EaFNScXZSTVUybEdTenQ3Q3U1eGIwSEoKbEk0TVp0eGt3MmFic3VQNit6S0ZZYmNwTy9XeHowcnY4Q0VlbmdnbVM0RnBKY2VzakxtcWFXSit0TFg4ejlyMAozMURsV0o0aXpQaU15Ym4rQTU4aXFMdWlEUlNpTDdrWUI4WEdidm1yQ21RdE9mL05tRGtaRDhLcmRMdWNJcXhMClVjdjJTdFhQSFY1NE9pczF2S1hSTXNWKzZJS3YrK28vbUVZU0pZK2poUmlRZ3loS25UTlhXUmhNQ25tOEZjejYKMHZBS1ZMZVpZcTAxeVV6aVFwZjFUTmtwNVl0UjFWakYzYzVWYjNtOW1LZUp4dnRCVVFiekNsZjBXYmNkRUkwSApySTM5dUgyZzJyK1dmWFdaTDhvTGpGbEswekMrdGVSbTYxQkwKLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
    rules:
      - apiGroups: [""] # Core API group
        apiVersions: ["v1"]
        operations: ["CREATE"]
        resources: ["persistentvolumeclaims"]
    failurePolicy: Fail # Reject PVC creation if the webhook server is unreachable
    sideEffects: None
    admissionReviewVersions: ["v1"]
