auth:
  adminUser: root
  adminPassword: root

# ### to serve on existing domains subpath: https://sh-213.runailabs-cs.com/itay-keycloak/
# httpRelativePath: /itay-keycloak/
# ingress:
#   enabled: true
#   hostname: sh-213.runailabs-cs.com
#   hostnameStrict: true
#   pathType: Prefix
#   ingressClassName: nginx
#   tls: true
#   extraTls:
#   - hosts:
#     - sh-213.runailabs-cs.com
#     secretName: runai-backend-tls

## to serve on a separate domain: https://itay-keycloak-test.runailabs-cs.com/
ingress:
  enabled: true
  hostname: HOST_DOMAIN
  hostnameStrict: true
  ingressClassName: nginx
  tls: true
  extraTls:
  - hosts:
    - HOST_PATH
    secretName: HOST_TLS_SECRET

logging:
  level: DEBUG

### themes
initContainers:
- name: themes
  image: nginx
  command:
  - /bin/sh
  - -c
  - |
    apt-get update && apt-get install -y zip
    cd /tmp/ && pwd
    curl -L -o ./master.zip https://github.com/genny-project/keycloak-themes/archive/refs/heads/master.zip
    unzip ./master.zip
    cd ./keycloak-themes-master/themes
    rm -rf ./base/  ./keycloak/  ./keycloak-preview/
    mv ./* /keycloak/themes/
    cd /keycloak/themes/ && pwd
    ls -la
    rm -rf /tmp/master.zip && rm -rf /tmp/keycloak-themes-master/
  volumeMounts:
  - name: themes
    mountPath: /keycloak/themes
extraVolumeMounts:
- name: themes
  mountPath: /opt/bitnami/keycloak/themes
extraVolumes:
- name: themes
  emptyDir: {}
